### ISSUE TITLE
Postgres Count('x') Error - Invalid comparison operator

### ISSUE THREAD

**Issue by katcher** [isuru89/moodle-local_reminders#104]
Hello,
The following error apperaed in my postgres 9.6 DB when executing 

Clean Local Reminders Logs scheduled task

ERROR: operator does not exist: character varying >= integer at character 55
HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts.
STATEMENT: SELECT COUNT('x') FROM mdl_local_reminders WHERE time >= 1611850862

The function clean_local_reminders_logs function  around line 520
$recordcount = $DB->count_records_select(REMINDERS_CLEAN_TABLE, "time >= $cutofftime");
as well as 
$deletestatus = $DB->delete_records_select(REMINDERS_CLEAN_TABLE, "time < $cutofftime");

are affected.

I wonder why you have chosen character type for the time column of th elocal_reminders db.  It is a unix timestamp.  Why not assign it INT or BIGINT.

Short of that, i believe the following will fix the error without modifying the db structure of the local_reminders table:

$recordcount = $DB->count_records_select(REMINDERS_CLEAN_TABLE, "time >= **'$cutofftime'**");
as well as 
$deletestatus = $DB->delete_records_select(REMINDERS_CLEAN_TABLE, "time < **'$cutofftime'**");

I am not sure how this will affect other databases - mysql etc.

**Comment by isuru89** [comment]
Thank you for reporting @katcher 

I wonder how did I miss this. This table was the first table introduced with the very first version of the plugin.

Ideally, as you said, the column time must be a number type. And this needs to convert to that proper type. Maybe MySQL or other db versions do this cast implicitly.

I will plan a migration, rather than hacking the query.

**Comment by isuru89** [comment]
@katcher Also need some helpful information because I don't have much knowledge about the behavior of postgres.

Like, does this function works correctly in your deployment with Postgres? (https://github.com/isuru89/moodle-local_reminders/blob/master/lib.php#L387) 
So, if it works, that means Postgres can insert numbers into text columns, but can't compare it.

**Comment by ppv1979** [comment]
@isuru89, it seem that it still doesn't fixed in the last release of plugin.

Another way of fixing it is using cross-db functions in Moodle data manipulation API to convert varchar into integer:

$recordcount = $DB->count_records_select(REMINDERS_CLEAN_TABLE, $DB->sql_cast_char2int('time')." >= $cutofftime");

$deletestatus = $DB->delete_records_select(REMINDERS_CLEAN_TABLE, $DB->sql_cast_char2int('time')." < $cutofftime");

**Comment by isuru89** [comment]
@ppv1979 
I did not still release this fix with the official release (which is 2.4 (2021062000)).
I believe a proper data migration is required to fix this.

But really appreciate the tip for fixing in your latest comment. I'll try to incorporate this in a future release quickly.
Thanks

**Comment by ppv1979** [comment]
@isuru89 v2.5, released 5 days ago, also didn't fix this.

**Comment by isuru89** [comment]
@ppv1979 
True, because I am thinking about a proper solution with table changes since type conversion is not ideal.
I'll update this thread once I completed testing with data migration.

Thanks

**Comment by isuru89** [comment]
@ppv1979 
This is my current progress https://github.com/isuru89/moodle-local_reminders/pull/141/files

I don't have a moodle instance with Postgres for testing, so this gets delayed. It is better if you can test me this.

**Comment by ppv1979** [comment]
@isuru89 I've just test the conversion, using the pull above and it seems that everything is ok, the error is disappeared.
The only thing is that you should also fix the db/install.xml with the proper field type for new installations of the plugin.

**Comment by MURBASLMS** [comment]
hi, apparently this fixes this issue https://github.com/catalyst/moodle-local_reminders - any chance you could review and apply at some point please? cheers

**Comment by isuru89** [comment]
@MURBASLMS Thanks for your solution.

Any change, you could create a pull request to `release_2.0` branch from your repo to this repository? So, if everything is ok, I could merge and release a patch version soon.

Also I hope you have tested migrating from older plugin as well? And also for a different sql dialect as well? Because, as far as I understood, this issue occurred for the admins who uses Postgres. MySQL somehow worked due to type implicit conversion.

**Comment by isuru89** [comment]
Released with plugin v2.7
